services:
  nachschub_bot:
    build: ./NachschubBot
    environment:
      - BOT_KEY=${NACHSCHUB_API_KEY}
    restart: always

  ballkoenig_bot:
    build: ./BallkoenigBot
    environment:
      - BOT_KEY=${BALLKOENIG_API_KEY}
    restart: always
